const words = [
  { hangul: "안녕하세요", romanization: "annyeonghaseyo", translation: "Hello" },
  { hangul: "사랑", romanization: "sarang", translation: "Love" },
  { hangul: "학교", romanization: "hakgyo", translation: "School" },
  { hangul: "친구", romanization: "chingu", translation: "Friend" },
  { hangul: "의자", romanization: "uija", translation: "Chair" },
  { hangul: "컴퓨터", romanization: "keompyuteo", translation: "Computer" },
  { hangul: "비행기", romanization: "bihaenggi", translation: "Airplane" },
  { hangul: "물", romanization: "mul", translation: "Water" },
  { hangul: "사과", romanization: "sagwa", translation: "Apple" },
  { hangul: "책", romanization: "chaek", translation: "Book" },
  { hangul: "한국", romanization: "hanguk", translation: "Korea" },
  { hangul: "음식", romanization: "eumsik", translation: "Food" },
  { hangul: "여행", romanization: "yeohaeng", translation: "Travel" },
  { hangul: "사람", romanization: "saram", translation: "Person" },
  { hangul: "시간", romanization: "shigan", translation: "Time" },
  { hangul: "장소", romanization: "jangso", translation: "Place" },
  { hangul: "사진", romanization: "sajin", translation: "Photo" },
  { hangul: "동물", romanization: "dongmul", translation: "Animal" },
  { hangul: "가게", romanization: "gage", translation: "Store" },
  { hangul: "커피", romanization: "keopi", translation: "Coffee" },
  { hangul: "차", romanization: "cha", translation: "Tea" },
  { hangul: "버스", romanization: "beoseu", translation: "Bus" },
  { hangul: "지하철", romanization: "jihacheol", translation: "Subway" },
  { hangul: "서울", romanization: "seoul", translation: "Seoul" },
  { hangul: "아침", romanization: "achim", translation: "Morning" },
  { hangul: "점심", romanization: "jeomsim", translation: "Lunch" },
  { hangul: "저녁", romanization: "jeonyeok", translation: "Evening/Dinner" },
  { hangul: "누나", romanization: "nuna", translation: "Older sister (male)" },
  { hangul: "형", romanization: "hyeong", translation: "Older brother (male)" },
  { hangul: "동생", romanization: "dongsaeng", translation: "Younger sibling" },
  { hangul: "할머니", romanization: "halmeoni", translation: "Grandmother" },
  { hangul: "할아버지", romanization: "halabeoji", translation: "Grandfather" },
  { hangul: "어머니", romanization: "eomeoni", translation: "Mother" },
  { hangul: "아버지", romanization: "abeoji", translation: "Father" },
  { hangul: "선생님", romanization: "seonsaengnim", translation: "Teacher" },
  { hangul: "학생", romanization: "haksaeng", translation: "Student" },
  { hangul: "책상", romanization: "chaeksang", translation: "Desk" },
  { hangul: "의사", romanization: "uisa", translation: "Doctor" },
  { hangul: "병원", romanization: "byeongwon", translation: "Hospital" },
  { hangul: "약국", romanization: "yakguk", translation: "Pharmacy" },
  { hangul: "가수", romanization: "gasu", translation: "Singer" },
  { hangul: "노래", romanization: "norae", translation: "Song" },
  { hangul: "영화", romanization: "yeonghwa", translation: "Movie" },
  { hangul: "극장", romanization: "geukjang", translation: "Theater" },
  { hangul: "신발", romanization: "shinbal", translation: "Shoes" },
  { hangul: "옷", romanization: "ot", translation: "Clothes" },
  { hangul: "바지", romanization: "baji", translation: "Pants" },
  { hangul: "치마", romanization: "chima", translation: "Skirt" },
  { hangul: "모자", romanization: "moja", translation: "Hat" },
  { hangul: "안경", romanization: "angyeong", translation: "Glasses" },
  { hangul: "날씨", romanization: "nalssi", translation: "Weather" },
  { hangul: "비", romanization: "bi", translation: "Rain" },
  { hangul: "눈", romanization: "nun", translation: "Snow" },
  { hangul: "태양", romanization: "taeyang", translation: "Sun" },
  { hangul: "달", romanization: "dal", translation: "Moon" },
  { hangul: "별", romanization: "byeol", translation: "Star" },
  { hangul: "바다", romanization: "bada", translation: "Sea" },
  { hangul: "강", romanization: "gang", translation: "River" },
  { hangul: "산", romanization: "san", translation: "Mountain" },
  { hangul: "나무", romanization: "namu", translation: "Tree" },
  { hangul: "꽃", romanization: "kkot", translation: "Flower" },
  { hangul: "사탕", romanization: "satang", translation: "Candy" },
  { hangul: "초콜릿", romanization: "chokollit", translation: "Chocolate" },
  { hangul: "빵", romanization: "ppang", translation: "Bread" },
  { hangul: "고기", romanization: "gogi", translation: "Meat" },
  { hangul: "물고기", romanization: "mulgogi", translation: "Fish" },
  { hangul: "과일", romanization: "gwail", translation: "Fruit" },
  { hangul: "배", romanization: "bae", translation: "Pear" },
  { hangul: "포도", romanization: "podo", translation: "Grape" },
  { hangul: "딸기", romanization: "ttalgi", translation: "Strawberry" },
  { hangul: "귤", romanization: "gyul", translation: "Tangerine" },
  { hangul: "바나나", romanization: "banana", translation: "Banana" },
  { hangul: "오렌지", romanization: "orenji", translation: "Orange" },
  { hangul: "수박", romanization: "subak", translation: "Watermelon" },
  { hangul: "토마토", romanization: "tomato", translation: "Tomato" },
  { hangul: "감자", romanization: "gamja", translation: "Potato" },
  { hangul: "고구마", romanization: "goguma", translation: "Sweet potato" },
  { hangul: "양파", romanization: "yangpa", translation: "Onion" },
  { hangul: "마늘", romanization: "maneul", translation: "Garlic" },
  { hangul: "파", romanization: "pa", translation: "Green onion" },
  { hangul: "소금", romanization: "sogeum", translation: "Salt" },
  { hangul: "설탕", romanization: "seoltang", translation: "Sugar" },
  { hangul: "간장", romanization: "ganjang", translation: "Soy sauce" },
  { hangul: "기름", romanization: "gireum", translation: "Oil" },
  { hangul: "라면", romanization: "ramyeon", translation: "Ramen" },
  { hangul: "김치", romanization: "kimchi", translation: "Kimchi" },
  { hangul: "두부", romanization: "dubu", translation: "Tofu" },
  { hangul: "콩", romanization: "kong", translation: "Bean" },
  { hangul: "쌀", romanization: "ssal", translation: "Uncooked rice" },
  { hangul: "밥", romanization: "bap", translation: "Cooked rice/Meal" },
  { hangul: "국", romanization: "guk", translation: "Soup" },
  { hangul: "김밥", romanization: "gimbap", translation: "Kimbap" },
  { hangul: "불고기", romanization: "bulgogi", translation: "Bulgogi" },
  { hangul: "갈비", romanization: "galbi", translation: "Ribs" },
  { hangul: "찜", romanization: "jjim", translation: "Steamed dish" },
  { hangul: "탕", romanization: "tang", translation: "Soup (hearty)" },
  { hangul: "전", romanization: "jeon", translation: "Korean pancake" },
  { hangul: "떡", romanization: "tteok", translation: "Rice cake" },
  { hangul: "떡볶이", romanization: "tteokbokki", translation: "Spicy rice cakes" },
  { hangul: "만두", romanization: "mandu", translation: "Dumpling" },
  { hangul: "계란", romanization: "gyeran", translation: "Egg" },
  { hangul: "우유", romanization: "uyu", translation: "Milk" },
  { hangul: "주스", romanization: "juseu", translation: "Juice" },
  { hangul: "맥주", romanization: "maekju", translation: "Beer" },
  { hangul: "소주", romanization: "soju", translation: "Soju" },
  { hangul: "막걸리", romanization: "makgeolli", translation: "Makgeolli (rice wine)" },
  { hangul: "우체국", romanization: "ucheguk", translation: "Post office" },
  { hangul: "은행", romanization: "eunhaeng", translation: "Bank" },
  { hangul: "가방", romanization: "gabang", translation: "Bag" },
  { hangul: "열쇠", romanization: "yeolswe", translation: "Key" },
  { hangul: "문", romanization: "mun", translation: "Door" },
  { hangul: "창문", romanization: "changmun", translation: "Window" },
  { hangul: "신문", romanization: "sinmun", translation: "Newspaper" },
  { hangul: "편지", romanization: "pyeonji", translation: "Letter" },
  { hangul: "방", romanization: "bang", translation: "Room" },
  { hangul: "집", romanization: "jip", translation: "House" },
  { hangul: "아파트", romanization: "apateu", translation: "Apartment" },
  { hangul: "다리", romanization: "dari", translation: "Bridge" },
  { hangul: "길", romanization: "gil", translation: "Road" },
  { hangul: "거리", romanization: "geori", translation: "Street" },
  { hangul: "시장", romanization: "sijang", translation: "Market" },
  { hangul: "회사", romanization: "hoesa", translation: "Company" },
  { hangul: "공원", romanization: "gongwon", translation: "Park" },
  { hangul: "교실", romanization: "gyoshil", translation: "Classroom" },
  { hangul: "도서관", romanization: "doseogwan", translation: "Library" },
  { hangul: "서점", romanization: "seojeom", translation: "Bookstore" },
  { hangul: "편의점", romanization: "pyeonuijeom", translation: "Convenience store" },
  { hangul: "식당", romanization: "shikdang", translation: "Restaurant" },
  { hangul: "화장실", romanization: "hwajangshil", translation: "Bathroom" },
  { hangul: "방송국", romanization: "bangsongguk", translation: "Broadcasting station" },
  { hangul: "경찰서", romanization: "gyeongchalseo", translation: "Police station" },
  { hangul: "소방서", romanization: "sobangseo", translation: "Fire station" },
  { hangul: "차고", romanization: "chago", translation: "Garage" },
  { hangul: "차량", romanization: "charyang", translation: "Vehicle" },
  { hangul: "자동차", romanization: "jadongcha", translation: "Car" },
  { hangul: "오토바이", romanization: "otobai", translation: "Motorcycle" },
  { hangul: "자전거", romanization: "jajeongeo", translation: "Bicycle" },
  { hangul: "배", romanization: "bae", translation: "Pear" }
];

export default words;
